title: How Many Hours
description: "An offline Android time tracker for your projects. No cloud. No accounts. No ads. Just your hours."
url: "https://luisbosque.github.io"
baseurl: "/howmanyhours"

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
